
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */

#include "spice-widget-enums.h"
#include "spice-widget.h"

#define C_ENUM(v) ((gint) v)
#define C_FLAGS(v) ((guint) v)

/* enumerations from "spice-widget.h" */

GType
spice_display_key_event_get_type (void)
{
  static volatile gsize gtype_id = 0;
  static const GEnumValue values[] = {
    { C_ENUM(SPICE_DISPLAY_KEY_EVENT_PRESS), "SPICE_DISPLAY_KEY_EVENT_PRESS", "press" },
    { C_ENUM(SPICE_DISPLAY_KEY_EVENT_RELEASE), "SPICE_DISPLAY_KEY_EVENT_RELEASE", "release" },
    { C_ENUM(SPICE_DISPLAY_KEY_EVENT_CLICK), "SPICE_DISPLAY_KEY_EVENT_CLICK", "click" },
    { 0, NULL, NULL }
  };
  if (g_once_init_enter (&gtype_id)) {
    GType new_type = g_enum_register_static (g_intern_static_string ("SpiceDisplayKeyEvent"), values);
    g_once_init_leave (&gtype_id, new_type);
  }
  return (GType) gtype_id;
}

/* Generated data ends here */

