/* This file is generated by glib-genmarshal, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */
#pragma once

#include <glib-object.h>

G_BEGIN_DECLS

/* VOID:INT,INT (../src/spice-marshal.txt:1) */
extern
void g_cclosure_user_marshal_VOID__INT_INT (GClosure     *closure,
                                            GValue       *return_value,
                                            guint         n_param_values,
                                            const GValue *param_values,
                                            gpointer      invocation_hint,
                                            gpointer      marshal_data);

/* VOID:INT,INT,INT (../src/spice-marshal.txt:2) */
extern
void g_cclosure_user_marshal_VOID__INT_INT_INT (GClosure     *closure,
                                                GValue       *return_value,
                                                guint         n_param_values,
                                                const GValue *param_values,
                                                gpointer      invocation_hint,
                                                gpointer      marshal_data);

/* VOID:INT,INT,INT,INT (../src/spice-marshal.txt:3) */
extern
void g_cclosure_user_marshal_VOID__INT_INT_INT_INT (GClosure     *closure,
                                                    GValue       *return_value,
                                                    guint         n_param_values,
                                                    const GValue *param_values,
                                                    gpointer      invocation_hint,
                                                    gpointer      marshal_data);

/* VOID:UINT,UINT,UINT,UINT (../src/spice-marshal.txt:4) */
extern
void g_cclosure_user_marshal_VOID__UINT_UINT_UINT_UINT (GClosure     *closure,
                                                        GValue       *return_value,
                                                        guint         n_param_values,
                                                        const GValue *param_values,
                                                        gpointer      invocation_hint,
                                                        gpointer      marshal_data);

/* VOID:INT,INT,INT,INT,POINTER (../src/spice-marshal.txt:5) */
extern
void g_cclosure_user_marshal_VOID__INT_INT_INT_INT_POINTER (GClosure     *closure,
                                                            GValue       *return_value,
                                                            guint         n_param_values,
                                                            const GValue *param_values,
                                                            gpointer      invocation_hint,
                                                            gpointer      marshal_data);

/* VOID:INT,INT,INT,INT,INT,POINTER (../src/spice-marshal.txt:6) */
extern
void g_cclosure_user_marshal_VOID__INT_INT_INT_INT_INT_POINTER (GClosure     *closure,
                                                                GValue       *return_value,
                                                                guint         n_param_values,
                                                                const GValue *param_values,
                                                                gpointer      invocation_hint,
                                                                gpointer      marshal_data);

/* VOID:POINTER,INT (../src/spice-marshal.txt:7) */
extern
void g_cclosure_user_marshal_VOID__POINTER_INT (GClosure     *closure,
                                                GValue       *return_value,
                                                guint         n_param_values,
                                                const GValue *param_values,
                                                gpointer      invocation_hint,
                                                gpointer      marshal_data);

/* VOID:POINTER,BOOLEAN (../src/spice-marshal.txt:8) */
extern
void g_cclosure_user_marshal_VOID__POINTER_BOOLEAN (GClosure     *closure,
                                                    GValue       *return_value,
                                                    guint         n_param_values,
                                                    const GValue *param_values,
                                                    gpointer      invocation_hint,
                                                    gpointer      marshal_data);

/* BOOLEAN:POINTER,UINT (../src/spice-marshal.txt:9) */
extern
void g_cclosure_user_marshal_BOOLEAN__POINTER_UINT (GClosure     *closure,
                                                    GValue       *return_value,
                                                    guint         n_param_values,
                                                    const GValue *param_values,
                                                    gpointer      invocation_hint,
                                                    gpointer      marshal_data);

/* BOOLEAN:UINT (../src/spice-marshal.txt:10) */
extern
void g_cclosure_user_marshal_BOOLEAN__UINT (GClosure     *closure,
                                            GValue       *return_value,
                                            guint         n_param_values,
                                            const GValue *param_values,
                                            gpointer      invocation_hint,
                                            gpointer      marshal_data);

/* VOID:UINT,POINTER,UINT (../src/spice-marshal.txt:11) */
extern
void g_cclosure_user_marshal_VOID__UINT_POINTER_UINT (GClosure     *closure,
                                                      GValue       *return_value,
                                                      guint         n_param_values,
                                                      const GValue *param_values,
                                                      gpointer      invocation_hint,
                                                      gpointer      marshal_data);

/* VOID:UINT,UINT,POINTER,UINT (../src/spice-marshal.txt:12) */
extern
void g_cclosure_user_marshal_VOID__UINT_UINT_POINTER_UINT (GClosure     *closure,
                                                           GValue       *return_value,
                                                           guint         n_param_values,
                                                           const GValue *param_values,
                                                           gpointer      invocation_hint,
                                                           gpointer      marshal_data);

/* BOOLEAN:UINT,POINTER,UINT (../src/spice-marshal.txt:13) */
extern
void g_cclosure_user_marshal_BOOLEAN__UINT_POINTER_UINT (GClosure     *closure,
                                                         GValue       *return_value,
                                                         guint         n_param_values,
                                                         const GValue *param_values,
                                                         gpointer      invocation_hint,
                                                         gpointer      marshal_data);

/* BOOLEAN:UINT,UINT (../src/spice-marshal.txt:14) */
extern
void g_cclosure_user_marshal_BOOLEAN__UINT_UINT (GClosure     *closure,
                                                 GValue       *return_value,
                                                 guint         n_param_values,
                                                 const GValue *param_values,
                                                 gpointer      invocation_hint,
                                                 gpointer      marshal_data);

/* VOID:BOXED,BOXED (../src/spice-marshal.txt:15) */
extern
void g_cclosure_user_marshal_VOID__BOXED_BOXED (GClosure     *closure,
                                                GValue       *return_value,
                                                guint         n_param_values,
                                                const GValue *param_values,
                                                gpointer      invocation_hint,
                                                gpointer      marshal_data);

/* BOOLEAN:POINTER (../src/spice-marshal.txt:16) */
extern
void g_cclosure_user_marshal_BOOLEAN__POINTER (GClosure     *closure,
                                               GValue       *return_value,
                                               guint         n_param_values,
                                               const GValue *param_values,
                                               gpointer      invocation_hint,
                                               gpointer      marshal_data);


G_END_DECLS
