/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define ACL_HELPER_PATH "/home/pi/spice/usr/bin"

#define GETTEXT_PACKAGE "spice-gtk"

#define HAVE_ALLOCA 1

#define HAVE_ALLOCA_H 1

#define HAVE_ARPA_INET_H 1

#define HAVE_BUILTIN_MJPEG 1

#define HAVE_CLEARENV 1

#define HAVE_DLFCN_H 1

#define HAVE_DRAND48 1

#define HAVE_EGL 1

#define HAVE_EPOXY_EGL_H 1

#define HAVE_INTTYPES_H 1

#define HAVE_NETINET_IN_H 1

#define HAVE_OPUS 1

#define HAVE_PULSE 1

#define HAVE_REGEX_H 1

#define HAVE_SASL 1

#define HAVE_SETLINEBUF 1

#define HAVE_SIGACTION 1

#define HAVE_STDLIB_H 1

#define HAVE_STRTOK_R 1

#define HAVE_SYS_MMAN_H 1

#define HAVE_SYS_SOCKET_H 1

#define HAVE_SYS_STAT_H 1

#define HAVE_SYS_TYPES_H 1

#define HAVE_TERMIOS_H 1

#define HAVE_UNISTD_H 1

#define HAVE_X11_XKBLIB_H 1

#define LOCALE_DIR "/home/pi/spice/usr/share/locale"

#define PACKAGE_BUGREPORT "spice-devel@lists.freedesktop.org"

#define PACKAGE_STRING "spice-gtk 0.38"

#define PACKAGE_VERSION "0.38"

#define USE_LZ4 1

#define USE_SMARTCARD 1

#define VERSION "0.38"

#define WITH_UCONTEXT 1

